'use client';

import { useFormState, useFormStatus } from 'react-dom';
import type { SuperadminActionState } from '@/lib/superadmin-actions';

type Action = (state: SuperadminActionState, formData: FormData) => Promise<SuperadminActionState>;
function Submit({ label }: { label: string }) { const { pending } = useFormStatus(); return <button className="rounded-full bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950 disabled:opacity-50" disabled={pending} type="submit">{pending ? 'Procesando...' : label}</button>; }
function Message({ state }: { state: SuperadminActionState }) { return state.error ? <p className="text-sm text-red-200">{state.error}</p> : state.success ? <p className="text-sm text-emerald-200">{state.success}</p> : null; }

export function TenantForm({ action, tenant }: { action: Action; tenant: { id: string; activo: boolean; comision_pct: number; custom_domain: string | null } }) { const [state, formAction] = useFormState(action, {}); return <form action={formAction} className="grid gap-3 rounded-xl border border-slate-800 bg-slate-950/50 p-4"><input name="tenantId" type="hidden" value={tenant.id} /><label className="grid gap-1 text-xs text-slate-400">Dominio<input className="rounded-lg border border-slate-700 bg-slate-900 p-2 text-sm text-white" name="domain" defaultValue={tenant.custom_domain ?? ''} placeholder="streamish.mx" /></label><label className="grid gap-1 text-xs text-slate-400">Comisión %<input className="rounded-lg border border-slate-700 bg-slate-900 p-2 text-sm text-white" name="commission" type="number" min="0" max="100" step="0.01" defaultValue={tenant.comision_pct} /></label><label className="flex items-center gap-2 text-sm text-slate-300"><input name="active" type="checkbox" value="true" defaultChecked={tenant.activo} /> Activo</label><input name="active" type="hidden" value="false" /><Message state={state} /><Submit label="Guardar tenant" /></form>; }

export function OnboardingForm({ action, requestId }: { action: Action; requestId: string }) { const [state, formAction] = useFormState(action, {}); return <form action={formAction} className="grid gap-2"><input name="requestId" type="hidden" value={requestId} /><input name="note" className="rounded-lg border border-slate-700 bg-slate-950 p-2 text-sm text-white" placeholder="Nota opcional" /><div className="flex gap-2"><button className="rounded-full bg-emerald-500 px-3 py-2 text-xs font-semibold text-white" name="status" value="aprobada">Aprobar</button><button className="rounded-full bg-red-500/80 px-3 py-2 text-xs font-semibold text-white" name="status" value="rechazada">Rechazar</button></div><Message state={state} /></form>; }

export function CatalogForm({ action }: { action: Action }) { const [state, formAction] = useFormState(action, {}); return <form action={formAction} className="grid gap-3 rounded-2xl border border-slate-800 bg-slate-900/70 p-5"><input className="rounded-lg border border-slate-700 bg-slate-950 p-3 text-white" name="name" placeholder="Nombre" required /><input className="rounded-lg border border-slate-700 bg-slate-950 p-3 text-white" name="slug" placeholder="slug" required /><input className="rounded-lg border border-slate-700 bg-slate-950 p-3 text-white" name="iconUrl" placeholder="URL del icono" /><select className="rounded-lg border border-slate-700 bg-slate-950 p-3 text-white" name="active" defaultValue="true"><option value="true">Activo</option><option value="false">Inactivo</option></select><Message state={state} /><Submit label="Agregar servicio" /></form>; }

export function CommissionForm({ action, tenantId }: { action: Action; tenantId: string }) { const [state, formAction] = useFormState(action, {}); return <form action={formAction}><input name="tenantId" type="hidden" value={tenantId} /><Submit label="Marcar cobrado" /><Message state={state} /></form>; }
